# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 312b0bfe5ff60752ae224b808442c88a05cda652f8d2fa49e2b6486ad004550c2c4ff2b0036b9d5b7ac46097938374af411204ccdad9642b8fb4d4720df9aff0

test:
  secret_key_base: af4bbf37d829945228748dd49eaa8df3155dda14bcd920b617356d4f366dd0f76e15a4bb3525f7056a41bb76de7379f8564bdad9e67c14b2eb9d412dec19b2af

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
